### ISSUE TITLE
Different Fingerprint for same music file on same length

### ISSUE THREAD

**Issue by gautamverma** [parshap/node-fpcalc#3]
Why is generating to different fingerprint for the same music file with same length on 2 different machines? Any ideas.

One machine is AWS EC2 Instance running ubuntu 14.04 and other is a windows 8 machine. We have manually generated and verified it. Both are using same fpcalc command line tool for generating the fingerprint.  If more information is required we are happy to provide it. We are trying to use generated fingerprint as the ID for the file but if it not unique that it fails the whole purpose.

**Comment by gautamverma** [comment]
Yeah, we used the same file on two different machines. Due to this we resort to generate the fingerprint only on the Server and use the same everywhere.

**Comment by parshap** [comment]
This sounds like it may a bug in the underlying Chromaprint AcoustID implementation. As far as I know, the fingerprints should be the same for the same file on different machines. You may want to report an issue to them providing more information. https://bitbucket.org/acoustid/chromaprint/issues?status=new&status=open
